package scraping

class CombustivelScrapper {
    //returnaria uma lista
    fun getListPrecos(): String {
        return "REGIÃO\tESTADO\tMUNICÍPIO\tPRODUTO\n" +
                "SUL\tRIO GRANDE DO SUL\tALVORADA\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tAMERICANA\tETANOL HIDRATADO\n" +
                "CENTRO OESTE\tGOIAS\tANAPOLIS\tETANOL HIDRATADO\n" +
                "SUDESTE\tRIO DE JANEIRO\tANGRA DOS REIS\tETANOL HIDRATADO\n" +
                "NORDESTE\tSERGIPE\tARACAJU\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tARACATUBA\tETANOL HIDRATADO\n" +
                "NORDESTE\tALAGOAS\tARAPIRACA\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tASSIS\tETANOL HIDRATADO\n" +
                "SUL\tRIO GRANDE DO SUL\tBAGE\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tBARRETOS\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tBARUERI\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tBAURU\tETANOL HIDRATADO\n" +
                "NORDESTE\tPARAIBA\tBAYEUX\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tBEBEDOURO\tETANOL HIDRATADO\n" +
                "NORTE\tPARA\tBELEM\tETANOL HIDRATADO\n" +
                "SUDESTE\tRIO DE JANEIRO\tBELFORD ROXO\tETANOL HIDRATADO\n" +
                "SUDESTE\tMINAS GERAIS\tBELO HORIZONTE\tETANOL HIDRATADO\n" +
                "SUL\tSANTA CATARINA\tBIGUACU\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tBIRIGUI\tETANOL HIDRATADO\n" +
                "SUL\tSANTA CATARINA\tBLUMENAU\tETANOL HIDRATADO\n" +
                "NORTE\tRORAIMA\tBOA VISTA\tETANOL HIDRATADO\n" +
                "CENTRO OESTE\tDISTRITO FEDERAL\tBRASILIA\tETANOL HIDRATADO\n" +
                "NORDESTE\tPARAIBA\tCABEDELO\tETANOL HIDRATADO\n" +
                "SUDESTE\tSAO PAULO\tCACAPAVA\tETANOL HIDRATADO\n" +
                "SUL\tRIO GRANDE DO SUL\tCACHOEIRINHA\tETANOL HIDRATADO\n" +
                "SUDESTE\tESPIRITO SANTO\tCACHOEIRO DE ITAPEMIRIM\tETANOL HIDRATADO\n" +
                "NORDESTE\tBAHIA\tCAMACARI\tETANOL HIDRATADO\n"
    }

}
